<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="reference" nsURI="http://tools.vitruv/EChange/Java/Feature/Reference/1.0"
    nsPrefix="reference">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="modelName" value="Change"/>
    <details key="basePackage" value="tools.vitruv.domains.java.echange.feature"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="JavaInsertEReference">
    <eTypeParameters name="A">
      <eBounds eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eTypeParameters>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../tools.vitruv.framework.change.echange/metamodel/reference.ecore#//InsertEReference">
      <eTypeArguments eTypeParameter="#//JavaInsertEReference/A"/>
      <eTypeArguments eTypeParameter="#//JavaInsertEReference/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass feature.ecore#//JavaFeatureEChange">
      <eTypeArguments eTypeParameter="#//JavaInsertEReference/A"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaRemoveEReference">
    <eTypeParameters name="A">
      <eBounds eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eTypeParameters>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../tools.vitruv.framework.change.echange/metamodel/reference.ecore#//RemoveEReference">
      <eTypeArguments eTypeParameter="#//JavaRemoveEReference/A"/>
      <eTypeArguments eTypeParameter="#//JavaRemoveEReference/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass feature.ecore#//JavaFeatureEChange">
      <eTypeArguments eTypeParameter="#//JavaRemoveEReference/A"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaReplaceSingleValuedEReference">
    <eTypeParameters name="A">
      <eBounds eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eTypeParameters>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../tools.vitruv.framework.change.echange/metamodel/reference.ecore#//ReplaceSingleValuedEReference">
      <eTypeArguments eTypeParameter="#//JavaReplaceSingleValuedEReference/A"/>
      <eTypeArguments eTypeParameter="#//JavaReplaceSingleValuedEReference/T"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="ecore:EClass feature.ecore#//JavaFeatureEChange">
      <eTypeArguments eTypeParameter="#//JavaReplaceSingleValuedEReference/A"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
